# Generated by Django 4.2.16 on 2024-12-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0002_game_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='aga',
        ),
        migrations.AddField(
            model_name='buyer',
            name='age',
            field=models.IntegerField(default=17),
        ),
        migrations.AddField(
            model_name='buyer',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='game',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(default=1000),
        ),
        migrations.AddField(
            model_name='game',
            name='size',
            field=models.IntegerField(default=5),
        ),
    ]
