# Generated by Django 4.2.16 on 2024-12-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0004_alter_buyer_age_alter_buyer_balance_alter_game_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, default='default cost', max_digits=10)),
                ('power', models.IntegerField(default='default size')),
                ('description', models.TextField(default='default description')),
                ('buyer', models.ManyToManyField(related_name='kesseln', to='task1.buyer')),
            ],
        ),
    ]
