# Generated by Django 4.2.16 on 2024-12-19 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0009_burners'),
    ]

    operations = [
        migrations.RenameField(
            model_name='burners',
            old_name='cost',
            new_name='price',
        ),
    ]
