# Generated by Django 4.2.16 on 2024-12-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0010_rename_cost_burners_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('edge', models.IntegerField()),
                ('occupation', models.CharField(max_length=10)),
            ],
        ),
    ]
